### PR TITLE
Update aboutus.html

### PR DESCRIPTION
**Pull request by camille-sauvaud**
Fixed issue #4 

Please accept my modification

### CODE REVIEW

**Comment by jziegelmayer-ieseg** [comment]
You didn't link this to your issue. Make sure to do that or to close the issue manually after the merge.

**Comment by camille-sauvaud** [comment]
Yes I saw, I was trying to modify it. Can I or do I have to delete my pull request and start again ?

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : jziegelmayer-ieseg <notifications@github.com>
Envoyé : Tuesday, November 24, 2020 6:37:12 PM
À : alexis-jacquot/renteasy <renteasy@noreply.github.com>
Cc : SAUVAUD Camille <camille.sauvaud@ieseg.fr>; Author <author@noreply.github.com>
Objet : Re: [alexis-jacquot/renteasy] Update aboutus.html (#7)


You didn't link this to your issue. Make sure to do that or to close the issue manually after the merge.

**Comment by jziegelmayer-ieseg** [comment]
no, just add another comment and mention the issue with either fix, close, or... I forget the other linking words. I always use fix.

**Review by camille-sauvaud — COMMENTED** [review]
Fixed issue #4

**Pull request merged**
